import { createElement } from '@lwc/engine-dom';
import Fileupload_lwc_component from 'c/fileupload_lwc_component';

describe('c-fileupload-lwc-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-fileupload-lwc-component', {
            is: Fileupload_lwc_component
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});