@isTest
public class AdditionalChargesControllerTest {

    @testSetup
    static void setup() {
        User owner = new User(
            Email = 'owner112@example.com',
            Alias = 'owner',
            LastName='andy',
            ProfileId = UserInfo.getProfileId(),
            Username = 'owner43221163@example.com',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles'
        );
        insert owner;
        
        Project__c project = new  Project__c();
        project.Name = 'Veegaland Green Heights';
        project.Project_Type__c='Apartments';
        project.Finance_User__c = owner.Id;
        project.CRM_Manager__c =  owner.Id;
        insert project;
        
        Block__c block = new Block__c();
        block.Name='A';
        block.Project__c=project.id;
        insert block;
        
        Plot__c unit = new Plot__c();
        unit.Name = '101';
        unit.Status__c = 'Available';
        unit.Project__c = project.Id;
        unit.Block__c = 'A4';
        unit.Plot_Type__c = 'Residential';
        unit.Block1__c = block.Id;
        unit.Carpet_Area__c = 850;
        unit.Balcony_Sq_mts__c = 20;
        unit.Balcony_Area__c = 100;
        unit.BHK_Type__c = '3 BHK + 2T';
        unit.Premium_Status__c = 'Premium';
        unit.Floor__c = '1';
        unit.Share__c = 'MHPL';
        unit.Facing__c = 'EAST';
        unit.Carpet_Sq_mts__c = 80;
        unit.CA__c = 75;
        unit.Built_up_area__c = 1200;
        unit.UDS__c = 300;
        unit.UDS_Sq_mts__c = 50;
        unit.Super_built_up_area__c = 1500;
        unit.Price_Per_Sq_Ft__c = 5000;
        unit.Floor_Rise__c = 200;
        unit.Premium_Charge__c = 100000;
        unit.Covered_Park_Parking__c = 50000;
        unit.Other_Charges__c = 20000;
        unit.Solar_Charges__c = 15000;
        unit.GST1__c = 18;
        unit.Floor__c = '30';
        insert unit;
        
        Plot__c unit1 = new Plot__c();
        unit1.Name = '105';
        unit1.Status__c = 'Available';
        unit1.Project__c = project.Id;
        unit1.Block__c = 'A4';
        unit1.Plot_Type__c = 'Residential';
        unit1.Block1__c = block.Id;
        unit1.Carpet_Area__c = 850;
        unit1.Balcony_Sq_mts__c = 20;
        unit1.Balcony_Area__c = 100;
        unit1.BHK_Type__c = '3 BHK + 2T';
        unit1.Premium_Status__c = 'Premium';
        unit1.Floor__c = '1';
        unit1.Share__c = 'MHPL';
        unit1.Facing__c = 'EAST';
        unit1.Carpet_Sq_mts__c = 80;
        unit1.CA__c = 75;
        unit1.Built_up_area__c = 1200;
        unit1.UDS__c = 300;
        unit1.UDS_Sq_mts__c = 50;
        unit1.Super_built_up_area__c = 1500;
        unit1.Price_Per_Sq_Ft__c = 5000;
        unit1.Floor_Rise__c = 200;
        unit.Premium_Charge__c = 100000;
        unit1.Covered_Park_Parking__c = 50000;
        unit1.Other_Charges__c = 20000;
        unit1.Solar_Charges__c = 15000;
        unit1.GST1__c = 18;
        unit1.Floor__c = '3';
        insert unit1;
        
        Booking__c book = new Booking__c();
        book.Followup_Date__c = system.today();
        book.Followup_Subject__c = 'test22';
        book.Last_Comment__c = 'test22';
        book.Project__c = 'Veegaland Green Heights';
        book.Payment_Type__c = 'Custom';
        book.Sale_Agreement_Completed__c = false;
        book.Agreement_Amount_Cleared__c ='Received Partial Amount';
        book.Stage__c ='Welcome Email';
        book.Demand_Number__c = '12345'; 
        book.Project1__c = project.Id; 
        book.Date_of_Booking__c = System.today(); 
        book.Mode_Of_Payment__c = 'Credit Card';
        book.Funding_Type__c = 'Self';
        book.Plot__c = unit.Id;
        book.Loan_Sanction_Confirmed__c = true;
        book.Loan_Sanctioned_Amount__c = 10000;
        book.Finance_User__c = owner.Id;
        book.First_Applicant_Name__c = 'Akhil';
        book.Email1__c = 'Test@gamil.com';
        insert book;
        
        // Create test data for Additional_Charges__c object
        Additional_Charges__c additionalCharge1 = new Additional_Charges__c(
            Additional_Charge_Type__c ='Maintenance Charges',
            Booking__c = book.Id
        );
        insert additionalCharge1;
        
        Additional_Charges__c additionalCharge2 = new Additional_Charges__c(
            Additional_Charge_Type__c ='Maintenance Charges',
            Booking__c = book.Id
        );
        insert additionalCharge2;
    }

    @isTest
    static void testAdditionalChargesController() {
        // Fetch a test Additional_Charges__c record
        Additional_Charges__c additionalCharge = [SELECT Id FROM Additional_Charges__c  LIMIT 1];

        // Initialize the controller with the test record's standard controller
        ApexPages.StandardController stdController = new ApexPages.StandardController(additionalCharge);
        AdditionalChargesController controller = new AdditionalChargesController(stdController);

        // Test if totalcharge is calculated correctly
        
        // Test with null Total_Additional_Charge__c value
        Additional_Charges__c additionalChargeNull = [SELECT Id FROM Additional_Charges__c LIMIT 1];
        ApexPages.StandardController stdControllerNull = new ApexPages.StandardController(additionalChargeNull);
        AdditionalChargesController controllerNull = new AdditionalChargesController(stdControllerNull);
        
    }

    @isTest
    static void testGetFormattedDate() {
        Additional_Charges__c additionalCharge = [SELECT Id FROM Additional_Charges__c LIMIT 1];
        ApexPages.StandardController stdController = new ApexPages.StandardController(additionalCharge);
        AdditionalChargesController controller = new AdditionalChargesController(stdController);

        // Test getFormattedDate method
        Date testDate = Date.newInstance(2024, 8, 31);
        String formattedDate = controller.getFormattedDate(testDate);
    }


}