public class bookingcancleTest {
     /*
    @isTest
    static void testDoPost() {
        String jsonRequestData = '{"BookingId": "810", "Status": "Cancellation"}';
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/api/Booking/data';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(jsonRequestData);
        
        RestResponse response = new RestResponse();
        
        
        Test.startTest();
        RestContext.request = request;
        RestContext.response = response;
        bookingcancle.doPost();
        bookingcancle.testcover();
        Test.stopTest();
        
        
    }
    */
}